version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
      - node app.js

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
